POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "d@gmail.com",
  "password": "12345689"
}

###
POST http://localhost:3000/api/verification
Content-Type: application/json

{
  "code": 254039,
  "email": "d@gmail.com"
}

###
PUT http://localhost:3000/api/register

###
PATCH http://localhost:3000/api/company

###
PATCH http://localhost:3000/api/logo



###
POST http://localhost:3000/api/login

###