#Registro usuario1
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "bydartex@gmail.com",
  "password": "12345689"
}

###Verificacion usuario1
POST http://localhost:3000/api/verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI

{
  "email": "bydartex@gmail.com",
  "code": "102274"
}

###login usuario1
POST http://localhost:3000/api/user/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI

{
  "email": "bydartex@gmail.com",
  "password": "12345689"
}
###Completar info de usuario1
PATCH http://localhost:3000/api/user/complete-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI

{
  "name": "Nicolas",
  "surname":"Graullera",
  "nif":"1234567Z"
}
###Registro usuario2
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "usafan.dev@gmail.com",
  "password": "12345689"
}

###Verificacion usuario2
POST http://localhost:3000/api/verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGRiM2I5YTI4NjU0MGYyNGI0MjgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1NDI4LCJleHAiOjE3NDM1MzE4Mjh9._Gfno2-MmQVmofA5zuoxc5m51353wXh3g5v4GuHv9Io

{
  "email": "usafan.dev@gmail.com",
  "code": "316465"
}

###Creacion de empresa usuario1
PUT http://localhost:3000/api/company/create-company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI

{
  "boss":"bydartex@gmail.com",
  "company": {
    "name": "Servitop, SL.",
    "cif": "BXXXXXXXX",
    "street": "Carlos V",
    "number": 22,
    "postal": "28936",
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###usuario2 agrega usuario a la empresa de usuario1, error
PATCH http://localhost:3000/api/company/add-user-company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGRiM2I5YTI4NjU0MGYyNGI0MjgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1NDI4LCJleHAiOjE3NDM1MzE4Mjh9._Gfno2-MmQVmofA5zuoxc5m51353wXh3g5v4GuHv9Io

{
  "cif":"BXXXXXXXX",
  "employees":["bydartex.dev@gmail.com"]
}
###usuario1 agrega usuario a la empresa de usuario1, correcto
PATCH http://localhost:3000/api/company/add-user-company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI

{
  "cif":"BXXXXXXXX",
  "employees":["usafan.dev@gmail.com"]
}

###Logo usuario1
POST http://localhost:3000/api/logo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI

--boundary123
Content-Disposition: form-data; name="image"; filename="wp1892116-kimi-no-na-wa-wallpapers.png"
Content-Type: image/png

< ./wp1892116-kimi-no-na-wa-wallpapers.png
--boundary123--

###Get usuario1
GET http://localhost:3000/api/user/me 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI


###Get empresa usuario1, correcto
GET http://localhost:3000/api/company/my-company?cif=BXXXXXXXX
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGNlZDhjZmY5ZDE3NTQ5YWQxNjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1MjMwLCJleHAiOjE3NDM1MzE2MzB9.1towpn4mwT0fO1XbBygsV1UP9CaT6a3TabnzURt0kXI

###Get empresa usuario2, incorrecto
GET http://localhost:3000/api/company/my-company?cif=BXXXXXXXX
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhZGRiM2I5YTI4NjU0MGYyNGI0MjgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQ1NDI4LCJleHAiOjE3NDM1MzE4Mjh9._Gfno2-MmQVmofA5zuoxc5m51353wXh3g5v4GuHv9Io

###







